### ISSUE TITLE
What is the need of sendEmail module?

### ISSUE THREAD

**Issue by gunalabs** [sridhar-5/cab_hiring_backend#1]
Would be related to know the job, purpose and relevance of **sendEmail** module.

**Comment by sridhar-5** [comment]
to send emails to people when they forget passwords and push booking confirmations

**Comment by sridhar-5** [comment]
passports directory is not actually required **deleted** that already. that is coming in the next commit. Excuse me for that. 

Thanks.

**Comment by gunalabs** [comment]
> passports directory is not actually required **deleted** that already. that is coming in the next commit. Excuse me for that.
> 
> Thanks.

**Comment by gunalabs** [comment]
> passports directory is not actually required **deleted** that already. that is coming in the next commit. Excuse me for that.
> 
> Thanks.

No issues. But kindly keep the issues tracking clean and discussions within the topic of the issue
